version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/Fangsrepo/Aflinn/FangsdataWebSite/web-app
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/Fangsrepo/Aflinn/FangsdataWebSite/web-app

      - node/with-cache:
          steps:
            - run: npm install
            - run: npm lint
workflows:
    build-and-test:
      jobs:
        - build-and-test
